= Quarkus Iris - Event Driven Architecture Extension

Quarkus extension enabling event driven communication between quarkus services.

== Instructions

Compile and test the project:

[source,bash]
----
mvn verify
----

=== Project structure

* link:deployment/[] - Build time part of the extension. Annotation scanning, registration of consumers, etc.
* link:integration-tests/[] - Integration tests for the extension.
* link:runtime/[] - Run time part of the extension. Consumer and producer classes, etc.

== Extension configuration
Extension uses Quarkus RabbitMQ Connector Configuration https://quarkus.io/guides/rabbitmq-reference#configuration-reference

- `rabbitmq-host` - AMQP message broker address. Default value is read from *_io.vertx.rabbitmq.RabbitMQOptions.DEFAULT_HOST_*.
- `rabbitmq-port` - AMQP message broker port.
Default value is *_5672_*
- `rabbitmq-username` - AMQP authenticated connection username. Default value is read from *_io.vertx.rabbitmq.RabbitMQOptions.DEFAULT_USER_*
- `rabbitmq-password` - AMQP authenticated connection password. Default value is read from *_io.vertx.rabbitmq.RabbitMQOptions.DEFAULT_PASSWORD_*
- `rabbitmq-ssl` - AMQP connection uses SSL. Default value is `false`
- `rabbitmq-virtual-host` - AMQP virtual host. Default value is read from *_io.vertx.rabbitmq.RabbitMQOptions.DEFAULT_VIRTUAL_HOST_*
