name: Build & test
"on":
  push:
    branches:
      - '**'
    tags:
      - v*
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          overwrite-settings: false
      - shell: sh
        run: "mvn verify -Dci=${{ github.run_id }} -ntp"
