name: Build & test
"on":
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request_target:
    branches:
      - 'main'
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 21 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
          #overwrite-settings: false
      - shell: sh
        run: mvn --batch-mode verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
